/**
 * Stardust API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-06-15T19:52:41Z
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.5.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "StardustCoreSDK/model/SDOrderGetAllResponse.h"

namespace gg {
namespace stardust {
namespace coresdk {
namespace model {



SDOrderGetAllResponse::SDOrderGetAllResponse()
{
    m_OfferedBy = utility::conversions::to_string_t("");
    m_OfferedByIsSet = false;
    m_AcceptedBy = utility::conversions::to_string_t("");
    m_AcceptedByIsSet = false;
    m_TokensRequestedIsSet = false;
    m_TokensOfferedIsSet = false;
    m_Status = utility::conversions::to_string_t("");
    m_StatusIsSet = false;
}

SDOrderGetAllResponse::~SDOrderGetAllResponse()
{
}

void SDOrderGetAllResponse::validate()
{
    // TODO: implement validation
}

web::json::value SDOrderGetAllResponse::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_OfferedByIsSet)
    {
        val[utility::conversions::to_string_t(U("offeredBy"))] = ModelBase::toJson(m_OfferedBy);
    }
    if(m_AcceptedByIsSet)
    {
        val[utility::conversions::to_string_t(U("acceptedBy"))] = ModelBase::toJson(m_AcceptedBy);
    }
    if(m_TokensRequestedIsSet)
    {
        val[utility::conversions::to_string_t(U("tokensRequested"))] = ModelBase::toJson(m_TokensRequested);
    }
    if(m_TokensOfferedIsSet)
    {
        val[utility::conversions::to_string_t(U("tokensOffered"))] = ModelBase::toJson(m_TokensOffered);
    }
    if(m_StatusIsSet)
    {
        val[utility::conversions::to_string_t(U("status"))] = ModelBase::toJson(m_Status);
    }

    return val;
}

bool SDOrderGetAllResponse::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("offeredBy"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("offeredBy")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setOfferedBy;
            ok &= ModelBase::fromJson(fieldValue, refVal_setOfferedBy);
            setOfferedBy(refVal_setOfferedBy);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("acceptedBy"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("acceptedBy")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setAcceptedBy;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAcceptedBy);
            setAcceptedBy(refVal_setAcceptedBy);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("tokensRequested"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("tokensRequested")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<SDOrderGetAllResponse_tokensRequested_inner>> refVal_setTokensRequested;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTokensRequested);
            setTokensRequested(refVal_setTokensRequested);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("tokensOffered"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("tokensOffered")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<SDOrderGetAllResponse_tokensRequested_inner>> refVal_setTokensOffered;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTokensOffered);
            setTokensOffered(refVal_setTokensOffered);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("status"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("status")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setStatus;
            ok &= ModelBase::fromJson(fieldValue, refVal_setStatus);
            setStatus(refVal_setStatus);
        }
    }
    return ok;
}

void SDOrderGetAllResponse::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_OfferedByIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("offeredBy")), m_OfferedBy));
    }
    if(m_AcceptedByIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("acceptedBy")), m_AcceptedBy));
    }
    if(m_TokensRequestedIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("tokensRequested")), m_TokensRequested));
    }
    if(m_TokensOfferedIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("tokensOffered")), m_TokensOffered));
    }
    if(m_StatusIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("status")), m_Status));
    }
}

bool SDOrderGetAllResponse::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("offeredBy"))))
    {
        utility::string_t refVal_setOfferedBy;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("offeredBy"))), refVal_setOfferedBy );
        setOfferedBy(refVal_setOfferedBy);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("acceptedBy"))))
    {
        utility::string_t refVal_setAcceptedBy;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("acceptedBy"))), refVal_setAcceptedBy );
        setAcceptedBy(refVal_setAcceptedBy);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("tokensRequested"))))
    {
        std::vector<std::shared_ptr<SDOrderGetAllResponse_tokensRequested_inner>> refVal_setTokensRequested;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("tokensRequested"))), refVal_setTokensRequested );
        setTokensRequested(refVal_setTokensRequested);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("tokensOffered"))))
    {
        std::vector<std::shared_ptr<SDOrderGetAllResponse_tokensRequested_inner>> refVal_setTokensOffered;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("tokensOffered"))), refVal_setTokensOffered );
        setTokensOffered(refVal_setTokensOffered);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("status"))))
    {
        utility::string_t refVal_setStatus;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("status"))), refVal_setStatus );
        setStatus(refVal_setStatus);
    }
    return ok;
}

utility::string_t SDOrderGetAllResponse::getOfferedBy() const
{
    return m_OfferedBy;
}

void SDOrderGetAllResponse::setOfferedBy(const utility::string_t& value)
{
    m_OfferedBy = value;
    m_OfferedByIsSet = true;
}

bool SDOrderGetAllResponse::offeredByIsSet() const
{
    return m_OfferedByIsSet;
}

void SDOrderGetAllResponse::unsetOfferedBy()
{
    m_OfferedByIsSet = false;
}
utility::string_t SDOrderGetAllResponse::getAcceptedBy() const
{
    return m_AcceptedBy;
}

void SDOrderGetAllResponse::setAcceptedBy(const utility::string_t& value)
{
    m_AcceptedBy = value;
    m_AcceptedByIsSet = true;
}

bool SDOrderGetAllResponse::acceptedByIsSet() const
{
    return m_AcceptedByIsSet;
}

void SDOrderGetAllResponse::unsetAcceptedBy()
{
    m_AcceptedByIsSet = false;
}
std::vector<std::shared_ptr<SDOrderGetAllResponse_tokensRequested_inner>>& SDOrderGetAllResponse::getTokensRequested()
{
    return m_TokensRequested;
}

void SDOrderGetAllResponse::setTokensRequested(const std::vector<std::shared_ptr<SDOrderGetAllResponse_tokensRequested_inner>>& value)
{
    m_TokensRequested = value;
    m_TokensRequestedIsSet = true;
}

bool SDOrderGetAllResponse::tokensRequestedIsSet() const
{
    return m_TokensRequestedIsSet;
}

void SDOrderGetAllResponse::unsetTokensRequested()
{
    m_TokensRequestedIsSet = false;
}
std::vector<std::shared_ptr<SDOrderGetAllResponse_tokensRequested_inner>>& SDOrderGetAllResponse::getTokensOffered()
{
    return m_TokensOffered;
}

void SDOrderGetAllResponse::setTokensOffered(const std::vector<std::shared_ptr<SDOrderGetAllResponse_tokensRequested_inner>>& value)
{
    m_TokensOffered = value;
    m_TokensOfferedIsSet = true;
}

bool SDOrderGetAllResponse::tokensOfferedIsSet() const
{
    return m_TokensOfferedIsSet;
}

void SDOrderGetAllResponse::unsetTokensOffered()
{
    m_TokensOfferedIsSet = false;
}
utility::string_t SDOrderGetAllResponse::getStatus() const
{
    return m_Status;
}

void SDOrderGetAllResponse::setStatus(const utility::string_t& value)
{
    m_Status = value;
    m_StatusIsSet = true;
}

bool SDOrderGetAllResponse::statusIsSet() const
{
    return m_StatusIsSet;
}

void SDOrderGetAllResponse::unsetStatus()
{
    m_StatusIsSet = false;
}
}
}
}
}


