/**
 * Stardust API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-06-15T19:52:41Z
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.5.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "StardustCoreSDK/model/SDTemplateGetTokensResponse_token.h"

namespace gg {
namespace stardust {
namespace coresdk {
namespace model {



SDTemplateGetTokensResponse_token::SDTemplateGetTokensResponse_token()
{
    m_Id = 0;
    m_IdIsSet = false;
    m_Amount = utility::conversions::to_string_t("");
    m_AmountIsSet = false;
    m_TemplateId = 0;
    m_TemplateIdIsSet = false;
    m_Name = utility::conversions::to_string_t("");
    m_NameIsSet = false;
    m_PropsIsSet = false;
    m_PublicMetadataIsSet = false;
}

SDTemplateGetTokensResponse_token::~SDTemplateGetTokensResponse_token()
{
}

void SDTemplateGetTokensResponse_token::validate()
{
    // TODO: implement validation
}

web::json::value SDTemplateGetTokensResponse_token::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_IdIsSet)
    {
        val[utility::conversions::to_string_t(U("id"))] = ModelBase::toJson(m_Id);
    }
    if(m_AmountIsSet)
    {
        val[utility::conversions::to_string_t(U("amount"))] = ModelBase::toJson(m_Amount);
    }
    if(m_TemplateIdIsSet)
    {
        val[utility::conversions::to_string_t(U("templateId"))] = ModelBase::toJson(m_TemplateId);
    }
    if(m_NameIsSet)
    {
        val[utility::conversions::to_string_t(U("name"))] = ModelBase::toJson(m_Name);
    }
    if(m_PropsIsSet)
    {
        val[utility::conversions::to_string_t(U("props"))] = ModelBase::toJson(m_Props);
    }
    if(m_PublicMetadataIsSet)
    {
        val[utility::conversions::to_string_t(U("publicMetadata"))] = ModelBase::toJson(m_PublicMetadata);
    }

    return val;
}

bool SDTemplateGetTokensResponse_token::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("id")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setId);
            setId(refVal_setId);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("amount"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("amount")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setAmount;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAmount);
            setAmount(refVal_setAmount);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("templateId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("templateId")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setTemplateId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTemplateId);
            setTemplateId(refVal_setTemplateId);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("name"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("name")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setName);
            setName(refVal_setName);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("props"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("props")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<SDTemplateGetTokensResponse_token_props> refVal_setProps;
            ok &= ModelBase::fromJson(fieldValue, refVal_setProps);
            setProps(refVal_setProps);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("publicMetadata"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("publicMetadata")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Object> refVal_setPublicMetadata;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPublicMetadata);
            setPublicMetadata(refVal_setPublicMetadata);
        }
    }
    return ok;
}

void SDTemplateGetTokensResponse_token::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_IdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("id")), m_Id));
    }
    if(m_AmountIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("amount")), m_Amount));
    }
    if(m_TemplateIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("templateId")), m_TemplateId));
    }
    if(m_NameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("name")), m_Name));
    }
    if(m_PropsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("props")), m_Props));
    }
    if(m_PublicMetadataIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("publicMetadata")), m_PublicMetadata));
    }
}

bool SDTemplateGetTokensResponse_token::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("id"))))
    {
        int32_t refVal_setId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("id"))), refVal_setId );
        setId(refVal_setId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("amount"))))
    {
        utility::string_t refVal_setAmount;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("amount"))), refVal_setAmount );
        setAmount(refVal_setAmount);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("templateId"))))
    {
        int32_t refVal_setTemplateId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("templateId"))), refVal_setTemplateId );
        setTemplateId(refVal_setTemplateId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("name"))))
    {
        utility::string_t refVal_setName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("name"))), refVal_setName );
        setName(refVal_setName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("props"))))
    {
        std::shared_ptr<SDTemplateGetTokensResponse_token_props> refVal_setProps;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("props"))), refVal_setProps );
        setProps(refVal_setProps);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("publicMetadata"))))
    {
        std::shared_ptr<Object> refVal_setPublicMetadata;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("publicMetadata"))), refVal_setPublicMetadata );
        setPublicMetadata(refVal_setPublicMetadata);
    }
    return ok;
}

int32_t SDTemplateGetTokensResponse_token::getId() const
{
    return m_Id;
}

void SDTemplateGetTokensResponse_token::setId(int32_t value)
{
    m_Id = value;
    m_IdIsSet = true;
}

bool SDTemplateGetTokensResponse_token::idIsSet() const
{
    return m_IdIsSet;
}

void SDTemplateGetTokensResponse_token::unsetId()
{
    m_IdIsSet = false;
}
utility::string_t SDTemplateGetTokensResponse_token::getAmount() const
{
    return m_Amount;
}

void SDTemplateGetTokensResponse_token::setAmount(const utility::string_t& value)
{
    m_Amount = value;
    m_AmountIsSet = true;
}

bool SDTemplateGetTokensResponse_token::amountIsSet() const
{
    return m_AmountIsSet;
}

void SDTemplateGetTokensResponse_token::unsetAmount()
{
    m_AmountIsSet = false;
}
int32_t SDTemplateGetTokensResponse_token::getTemplateId() const
{
    return m_TemplateId;
}

void SDTemplateGetTokensResponse_token::setTemplateId(int32_t value)
{
    m_TemplateId = value;
    m_TemplateIdIsSet = true;
}

bool SDTemplateGetTokensResponse_token::templateIdIsSet() const
{
    return m_TemplateIdIsSet;
}

void SDTemplateGetTokensResponse_token::unsetTemplateId()
{
    m_TemplateIdIsSet = false;
}
utility::string_t SDTemplateGetTokensResponse_token::getName() const
{
    return m_Name;
}

void SDTemplateGetTokensResponse_token::setName(const utility::string_t& value)
{
    m_Name = value;
    m_NameIsSet = true;
}

bool SDTemplateGetTokensResponse_token::nameIsSet() const
{
    return m_NameIsSet;
}

void SDTemplateGetTokensResponse_token::unsetName()
{
    m_NameIsSet = false;
}
std::shared_ptr<SDTemplateGetTokensResponse_token_props> SDTemplateGetTokensResponse_token::getProps() const
{
    return m_Props;
}

void SDTemplateGetTokensResponse_token::setProps(const std::shared_ptr<SDTemplateGetTokensResponse_token_props>& value)
{
    m_Props = value;
    m_PropsIsSet = true;
}

bool SDTemplateGetTokensResponse_token::propsIsSet() const
{
    return m_PropsIsSet;
}

void SDTemplateGetTokensResponse_token::unsetProps()
{
    m_PropsIsSet = false;
}
std::shared_ptr<Object> SDTemplateGetTokensResponse_token::getPublicMetadata() const
{
    return m_PublicMetadata;
}

void SDTemplateGetTokensResponse_token::setPublicMetadata(const std::shared_ptr<Object>& value)
{
    m_PublicMetadata = value;
    m_PublicMetadataIsSet = true;
}

bool SDTemplateGetTokensResponse_token::publicMetadataIsSet() const
{
    return m_PublicMetadataIsSet;
}

void SDTemplateGetTokensResponse_token::unsetPublicMetadata()
{
    m_PublicMetadataIsSet = false;
}
}
}
}
}


