/**
 * Stardust API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-06-15T19:52:41Z
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.5.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "StardustCoreSDK/model/SDTemplateCreateRequest_props.h"

namespace gg {
namespace stardust {
namespace coresdk {
namespace model {



SDTemplateCreateRequest_props::SDTemplateCreateRequest_props()
{
    m_ImmutableIsSet = false;
    m_r_mutableIsSet = false;
}

SDTemplateCreateRequest_props::~SDTemplateCreateRequest_props()
{
}

void SDTemplateCreateRequest_props::validate()
{
    // TODO: implement validation
}

web::json::value SDTemplateCreateRequest_props::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_ImmutableIsSet)
    {
        val[utility::conversions::to_string_t(U("immutable"))] = ModelBase::toJson(m_Immutable);
    }
    if(m_r_mutableIsSet)
    {
        val[utility::conversions::to_string_t(U("mutable"))] = ModelBase::toJson(m_r_mutable);
    }

    return val;
}

bool SDTemplateCreateRequest_props::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("immutable"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("immutable")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Object> refVal_setImmutable;
            ok &= ModelBase::fromJson(fieldValue, refVal_setImmutable);
            setImmutable(refVal_setImmutable);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("mutable"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("mutable")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Object> refVal_setRMutable;
            ok &= ModelBase::fromJson(fieldValue, refVal_setRMutable);
            setRMutable(refVal_setRMutable);
        }
    }
    return ok;
}

void SDTemplateCreateRequest_props::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_ImmutableIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("immutable")), m_Immutable));
    }
    if(m_r_mutableIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("mutable")), m_r_mutable));
    }
}

bool SDTemplateCreateRequest_props::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("immutable"))))
    {
        std::shared_ptr<Object> refVal_setImmutable;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("immutable"))), refVal_setImmutable );
        setImmutable(refVal_setImmutable);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("mutable"))))
    {
        std::shared_ptr<Object> refVal_setRMutable;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("mutable"))), refVal_setRMutable );
        setRMutable(refVal_setRMutable);
    }
    return ok;
}

std::shared_ptr<Object> SDTemplateCreateRequest_props::getImmutable() const
{
    return m_Immutable;
}

void SDTemplateCreateRequest_props::setImmutable(const std::shared_ptr<Object>& value)
{
    m_Immutable = value;
    m_ImmutableIsSet = true;
}

bool SDTemplateCreateRequest_props::immutableIsSet() const
{
    return m_ImmutableIsSet;
}

void SDTemplateCreateRequest_props::unsetImmutable()
{
    m_ImmutableIsSet = false;
}
std::shared_ptr<Object> SDTemplateCreateRequest_props::getRMutable() const
{
    return m_r_mutable;
}

void SDTemplateCreateRequest_props::setRMutable(const std::shared_ptr<Object>& value)
{
    m_r_mutable = value;
    m_r_mutableIsSet = true;
}

bool SDTemplateCreateRequest_props::rMutableIsSet() const
{
    return m_r_mutableIsSet;
}

void SDTemplateCreateRequest_props::unsetr_mutable()
{
    m_r_mutableIsSet = false;
}
}
}
}
}


