/**
 * Stardust API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-07-25T00:59:12Z
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.5.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "StardustCoreSDK/model/SDTemplateMutateRequest.h"

namespace gg {
namespace stardust {
namespace coresdk {
namespace model {



SDTemplateMutateRequest::SDTemplateMutateRequest()
{
    m_TemplateId = 0;
    m_TemplateIdIsSet = false;
    m_PropsIsSet = false;
    m_PublicContractMetadataIsSet = false;
    m_PublicTokenMetadataIsSet = false;
}

SDTemplateMutateRequest::~SDTemplateMutateRequest()
{
}

void SDTemplateMutateRequest::validate()
{
    // TODO: implement validation
}

web::json::value SDTemplateMutateRequest::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_TemplateIdIsSet)
    {
        val[utility::conversions::to_string_t(U("templateId"))] = ModelBase::toJson(m_TemplateId);
    }
    if(m_PropsIsSet)
    {
        val[utility::conversions::to_string_t(U("props"))] = ModelBase::toJson(m_Props);
    }
    if(m_PublicContractMetadataIsSet)
    {
        val[utility::conversions::to_string_t(U("publicContractMetadata"))] = ModelBase::toJson(m_PublicContractMetadata);
    }
    if(m_PublicTokenMetadataIsSet)
    {
        val[utility::conversions::to_string_t(U("publicTokenMetadata"))] = ModelBase::toJson(m_PublicTokenMetadata);
    }

    return val;
}

bool SDTemplateMutateRequest::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("templateId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("templateId")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setTemplateId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTemplateId);
            setTemplateId(refVal_setTemplateId);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("props"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("props")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Object> refVal_setProps;
            ok &= ModelBase::fromJson(fieldValue, refVal_setProps);
            setProps(refVal_setProps);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("publicContractMetadata"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("publicContractMetadata")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Object> refVal_setPublicContractMetadata;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPublicContractMetadata);
            setPublicContractMetadata(refVal_setPublicContractMetadata);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("publicTokenMetadata"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("publicTokenMetadata")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Object> refVal_setPublicTokenMetadata;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPublicTokenMetadata);
            setPublicTokenMetadata(refVal_setPublicTokenMetadata);
        }
    }
    return ok;
}

void SDTemplateMutateRequest::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_TemplateIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("templateId")), m_TemplateId));
    }
    if(m_PropsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("props")), m_Props));
    }
    if(m_PublicContractMetadataIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("publicContractMetadata")), m_PublicContractMetadata));
    }
    if(m_PublicTokenMetadataIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("publicTokenMetadata")), m_PublicTokenMetadata));
    }
}

bool SDTemplateMutateRequest::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("templateId"))))
    {
        int32_t refVal_setTemplateId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("templateId"))), refVal_setTemplateId );
        setTemplateId(refVal_setTemplateId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("props"))))
    {
        std::shared_ptr<Object> refVal_setProps;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("props"))), refVal_setProps );
        setProps(refVal_setProps);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("publicContractMetadata"))))
    {
        std::shared_ptr<Object> refVal_setPublicContractMetadata;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("publicContractMetadata"))), refVal_setPublicContractMetadata );
        setPublicContractMetadata(refVal_setPublicContractMetadata);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("publicTokenMetadata"))))
    {
        std::shared_ptr<Object> refVal_setPublicTokenMetadata;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("publicTokenMetadata"))), refVal_setPublicTokenMetadata );
        setPublicTokenMetadata(refVal_setPublicTokenMetadata);
    }
    return ok;
}

int32_t SDTemplateMutateRequest::getTemplateId() const
{
    return m_TemplateId;
}

void SDTemplateMutateRequest::setTemplateId(int32_t value)
{
    m_TemplateId = value;
    m_TemplateIdIsSet = true;
}

bool SDTemplateMutateRequest::templateIdIsSet() const
{
    return m_TemplateIdIsSet;
}

void SDTemplateMutateRequest::unsetTemplateId()
{
    m_TemplateIdIsSet = false;
}
std::shared_ptr<Object> SDTemplateMutateRequest::getProps() const
{
    return m_Props;
}

void SDTemplateMutateRequest::setProps(const std::shared_ptr<Object>& value)
{
    m_Props = value;
    m_PropsIsSet = true;
}

bool SDTemplateMutateRequest::propsIsSet() const
{
    return m_PropsIsSet;
}

void SDTemplateMutateRequest::unsetProps()
{
    m_PropsIsSet = false;
}
std::shared_ptr<Object> SDTemplateMutateRequest::getPublicContractMetadata() const
{
    return m_PublicContractMetadata;
}

void SDTemplateMutateRequest::setPublicContractMetadata(const std::shared_ptr<Object>& value)
{
    m_PublicContractMetadata = value;
    m_PublicContractMetadataIsSet = true;
}

bool SDTemplateMutateRequest::publicContractMetadataIsSet() const
{
    return m_PublicContractMetadataIsSet;
}

void SDTemplateMutateRequest::unsetPublicContractMetadata()
{
    m_PublicContractMetadataIsSet = false;
}
std::shared_ptr<Object> SDTemplateMutateRequest::getPublicTokenMetadata() const
{
    return m_PublicTokenMetadata;
}

void SDTemplateMutateRequest::setPublicTokenMetadata(const std::shared_ptr<Object>& value)
{
    m_PublicTokenMetadata = value;
    m_PublicTokenMetadataIsSet = true;
}

bool SDTemplateMutateRequest::publicTokenMetadataIsSet() const
{
    return m_PublicTokenMetadataIsSet;
}

void SDTemplateMutateRequest::unsetPublicTokenMetadata()
{
    m_PublicTokenMetadataIsSet = false;
}
}
}
}
}


