/**
 * Stardust API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-06-15T19:52:41Z
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.5.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#ifndef GG_STARDUST_CORESDK_TokenEndpointsApiGMock_H_
#define GG_STARDUST_CORESDK_TokenEndpointsApiGMock_H_

#include <gmock/gmock.h>

#include "TokenEndpointsApi.h"

namespace gg {
namespace stardust {
namespace coresdk {

using namespace gg::stardust::coresdk::model;


class  TokenEndpointsApiMock : public ITokenEndpointsApi
{
public:
    using Base = ITokenEndpointsApi;

    TokenEndpointsApiMock() = default;
    explicit TokenEndpointsApiMock( std::shared_ptr<ApiClient> apiClient ) { };
    ~TokenEndpointsApiMock() override = default;

    MOCK_METHOD1( tokenBurnPost, pplx::task<std::shared_ptr<Object>> (
        std::shared_ptr<SDTokenBurnRequest> sDTokenBurnRequest
    ) );
    MOCK_METHOD2( tokenGetGet, pplx::task<std::vector<std::shared_ptr<SDTokenGetResponse>>> (
        boost::optional<utility::string_t> tokenIds,
        boost::optional<utility::string_t> returnExplorerLinks
    ) );
    MOCK_METHOD1( tokenMintBulkPost, pplx::task<std::vector<int32_t>> (
        std::shared_ptr<SDTokenMintBulkRequest> sDTokenMintBulkRequest
    ) );
    MOCK_METHOD1( tokenMutatePut, pplx::task<std::shared_ptr<Object>> (
        std::shared_ptr<SDTokenMutateRequest> sDTokenMutateRequest
    ) );
    MOCK_METHOD2( tokenPropsRemoveDelete, pplx::task<std::shared_ptr<Object>> (
        utility::string_t tokenId,
        utility::string_t props
    ) );
    MOCK_METHOD1( tokenTransferPost, pplx::task<std::shared_ptr<Object>> (
        std::shared_ptr<SDTokenTransferRequest> sDTokenTransferRequest
    ) );
    MOCK_METHOD1( tokenWithdrawPost, pplx::task<std::shared_ptr<Object>> (
        std::shared_ptr<SDTokenWithdrawRequest> sDTokenWithdrawRequest
    ) );
};

}
}
}

#endif /* GG_STARDUST_CORESDK_TokenEndpointsApiGMock_H_ */

