/**
 * Stardust API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-06-15T19:52:41Z
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.5.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * SDOrderGetAllResponse_tokensRequested_inner.h
 *
 * 
 */

#ifndef GG_STARDUST_CORESDK_MODEL_SDOrderGetAllResponse_tokensRequested_inner_H_
#define GG_STARDUST_CORESDK_MODEL_SDOrderGetAllResponse_tokensRequested_inner_H_


#include "StardustCoreSDK/ModelBase.h"


namespace gg {
namespace stardust {
namespace coresdk {
namespace model {


/// <summary>
/// 
/// </summary>
class  SDOrderGetAllResponse_tokensRequested_inner
    : public ModelBase
{
public:
    SDOrderGetAllResponse_tokensRequested_inner();
    virtual ~SDOrderGetAllResponse_tokensRequested_inner();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// SDOrderGetAllResponse_tokensRequested_inner members

    /// <summary>
    /// Token ID Number (unsigned 32 bit integer)
    /// </summary>
    int32_t getTokenId() const;
    bool tokenIdIsSet() const;
    void unsetTokenId();

    void setTokenId(int32_t value);

    /// <summary>
    /// Token ID Number (unsigned 32 bit integer)
    /// </summary>
    int32_t getAmount() const;
    bool amountIsSet() const;
    void unsetAmount();

    void setAmount(int32_t value);


protected:
    int32_t m_TokenId;
    bool m_TokenIdIsSet;
    int32_t m_Amount;
    bool m_AmountIsSet;
};


}
}
}
}

#endif /* GG_STARDUST_CORESDK_MODEL_SDOrderGetAllResponse_tokensRequested_inner_H_ */
