/**
 * Stardust API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-06-15T19:52:41Z
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.5.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * SDPlayerMutateRequest.h
 *
 * 
 */

#ifndef GG_STARDUST_CORESDK_MODEL_SDPlayerMutateRequest_H_
#define GG_STARDUST_CORESDK_MODEL_SDPlayerMutateRequest_H_


#include "StardustCoreSDK/ModelBase.h"

#include "StardustCoreSDK/Object.h"
#include <cpprest/details/basic_types.h>

namespace gg {
namespace stardust {
namespace coresdk {
namespace model {


/// <summary>
/// 
/// </summary>
class  SDPlayerMutateRequest
    : public ModelBase
{
public:
    SDPlayerMutateRequest();
    virtual ~SDPlayerMutateRequest();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// SDPlayerMutateRequest members

    /// <summary>
    /// Can be found with Player/getId(s).
    /// </summary>
    utility::string_t getPlayerId() const;
    bool playerIdIsSet() const;
    void unsetPlayerId();

    void setPlayerId(const utility::string_t& value);

    /// <summary>
    /// Specifies which properties you want to change (ex. {prop1: 5, prop2: 6, prop3: 7})
    /// </summary>
    std::shared_ptr<Object> getProps() const;
    bool propsIsSet() const;
    void unsetProps();

    void setProps(const std::shared_ptr<Object>& value);


protected:
    utility::string_t m_PlayerId;
    bool m_PlayerIdIsSet;
    std::shared_ptr<Object> m_Props;
    bool m_PropsIsSet;
};


}
}
}
}

#endif /* GG_STARDUST_CORESDK_MODEL_SDPlayerMutateRequest_H_ */
