/**
 * Stardust API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-07-25T00:59:12Z
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.5.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * SDPlayerWalletGetResponse.h
 *
 * This is the data output json model
 */

#ifndef GG_STARDUST_CORESDK_MODEL_SDPlayerWalletGetResponse_H_
#define GG_STARDUST_CORESDK_MODEL_SDPlayerWalletGetResponse_H_


#include "StardustCoreSDK/ModelBase.h"

#include "StardustCoreSDK/model/SDPlayerWalletGetResponse_wallet_inner.h"
#include <vector>

namespace gg {
namespace stardust {
namespace coresdk {
namespace model {

class SDPlayerWalletGetResponse_wallet_inner;

/// <summary>
/// This is the data output json model
/// </summary>
class  SDPlayerWalletGetResponse
    : public ModelBase
{
public:
    SDPlayerWalletGetResponse();
    virtual ~SDPlayerWalletGetResponse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// SDPlayerWalletGetResponse members

    /// <summary>
    /// An array of player wallets on the blockchain
    /// </summary>
    std::vector<std::shared_ptr<SDPlayerWalletGetResponse_wallet_inner>>& getWallet();
    bool walletIsSet() const;
    void unsetWallet();

    void setWallet(const std::vector<std::shared_ptr<SDPlayerWalletGetResponse_wallet_inner>>& value);


protected:
    std::vector<std::shared_ptr<SDPlayerWalletGetResponse_wallet_inner>> m_Wallet;
    bool m_WalletIsSet;
};


}
}
}
}

#endif /* GG_STARDUST_CORESDK_MODEL_SDPlayerWalletGetResponse_H_ */
