/**
 * Stardust API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-07-25T00:59:12Z
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.5.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * SDPlayerCreateJWTObject.h
 *
 * 
 */

#ifndef GG_STARDUST_CORESDK_MODEL_SDPlayerCreateJWTObject_H_
#define GG_STARDUST_CORESDK_MODEL_SDPlayerCreateJWTObject_H_


#include "StardustCoreSDK/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace gg {
namespace stardust {
namespace coresdk {
namespace model {


/// <summary>
/// 
/// </summary>
class  SDPlayerCreateJWTObject
    : public ModelBase
{
public:
    SDPlayerCreateJWTObject();
    virtual ~SDPlayerCreateJWTObject();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// SDPlayerCreateJWTObject members

    /// <summary>
    /// Your provider JWT name
    /// </summary>
    utility::string_t getType() const;
    bool typeIsSet() const;
    void unsetType();

    void setType(const utility::string_t& value);

    /// <summary>
    /// idToken of the user session
    /// </summary>
    utility::string_t getIdToken() const;
    bool idTokenIsSet() const;
    void unsetIdToken();

    void setIdToken(const utility::string_t& value);

    /// <summary>
    /// Access token of the user session
    /// </summary>
    utility::string_t getAccessToken() const;
    bool accessTokenIsSet() const;
    void unsetAccessToken();

    void setAccessToken(const utility::string_t& value);


protected:
    utility::string_t m_Type;
    bool m_TypeIsSet;
    utility::string_t m_IdToken;
    bool m_IdTokenIsSet;
    utility::string_t m_AccessToken;
    bool m_AccessTokenIsSet;
};


}
}
}
}

#endif /* GG_STARDUST_CORESDK_MODEL_SDPlayerCreateJWTObject_H_ */
