/**
 * Stardust API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-06-15T19:52:41Z
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.5.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * SDPlayerGetIdResponse.h
 *
 * This is the data output json model
 */

#ifndef GG_STARDUST_CORESDK_MODEL_SDPlayerGetIdResponse_H_
#define GG_STARDUST_CORESDK_MODEL_SDPlayerGetIdResponse_H_


#include "StardustCoreSDK/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace gg {
namespace stardust {
namespace coresdk {
namespace model {


/// <summary>
/// This is the data output json model
/// </summary>
class  SDPlayerGetIdResponse
    : public ModelBase
{
public:
    SDPlayerGetIdResponse();
    virtual ~SDPlayerGetIdResponse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// SDPlayerGetIdResponse members

    /// <summary>
    /// Player&#39;s Id
    /// </summary>
    utility::string_t getPlayerId() const;
    bool playerIdIsSet() const;
    void unsetPlayerId();

    void setPlayerId(const utility::string_t& value);


protected:
    utility::string_t m_PlayerId;
    bool m_PlayerIdIsSet;
};


}
}
}
}

#endif /* GG_STARDUST_CORESDK_MODEL_SDPlayerGetIdResponse_H_ */
