/**
 * Stardust API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-06-15T19:52:41Z
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.5.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * SDTokenMintBulkRequest.h
 *
 * 
 */

#ifndef GG_STARDUST_CORESDK_MODEL_SDTokenMintBulkRequest_H_
#define GG_STARDUST_CORESDK_MODEL_SDTokenMintBulkRequest_H_


#include "StardustCoreSDK/ModelBase.h"

#include "StardustCoreSDK/model/SDTokenMintBulkTokenObject.h"
#include <cpprest/details/basic_types.h>
#include <vector>

namespace gg {
namespace stardust {
namespace coresdk {
namespace model {

class SDTokenMintBulkTokenObject;

/// <summary>
/// 
/// </summary>
class  SDTokenMintBulkRequest
    : public ModelBase
{
public:
    SDTokenMintBulkRequest();
    virtual ~SDTokenMintBulkRequest();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// SDTokenMintBulkRequest members

    /// <summary>
    /// The player ID that was returned from player/create
    /// </summary>
    utility::string_t getPlayerId() const;
    bool playerIdIsSet() const;
    void unsetPlayerId();

    void setPlayerId(const utility::string_t& value);

    /// <summary>
    /// array of Token objects
    /// </summary>
    std::vector<std::shared_ptr<SDTokenMintBulkTokenObject>>& getTokenObjects();
    bool tokenObjectsIsSet() const;
    void unsetTokenObjects();

    void setTokenObjects(const std::vector<std::shared_ptr<SDTokenMintBulkTokenObject>>& value);


protected:
    utility::string_t m_PlayerId;
    bool m_PlayerIdIsSet;
    std::vector<std::shared_ptr<SDTokenMintBulkTokenObject>> m_TokenObjects;
    bool m_TokenObjectsIsSet;
};


}
}
}
}

#endif /* GG_STARDUST_CORESDK_MODEL_SDTokenMintBulkRequest_H_ */
